@baseUrl = http://localhost:3000
@authToken = {{authentication.response.body.access_token}}
@academicId = 5f9815d1-e8ee-4cc2-b828-916a48060a14
@eventId = 5d1158b5-66da-4841-be9c-5e1782c51fc6
@laboratoryId = bffcfcb8-ed2f-4324-b1c4-0198cacfe2c3
@subjectiveId = 5bc53c75-fcb4-4430-89cc-48c5515f725e
@subEventId = 4a25e69b-dd44-4178-9e6a-217bd9d3e08b

### Criar um acadêmico
# @name create_academic
POST {{baseUrl}}/academics/create
Content-Type: application/json

{
  "name": "Ana Costa",
  "email": "ana.costar@email.com",
  "phone": "00000000000000001",
  "RA": "1235465612",
  "password": "senha1233"
}

### Autenticar o acadêmico
# @name authentication
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "ana.coosstaa@email.com",
  "password": "senha123"
}

### Criar um evento (não depende de nada além da autenticação)
# @name create_event
POST {{baseUrl}}/events/create
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "teste",
  "description": "Evento anual da faculdade",
  "date": "2025-10-01T00:00:00.000Z"
}

### Visualização de todos os events
# @name fecth_event
GET  {{baseUrl}}/events/findAll?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}


### Criar um laboratório
# @name create_laboratory
POST {{baseUrl}}/laboratory/create
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "local": "Laboratório A101",
  "quanity": 40
}

### Visualizar todos os laboratórios
# @name fecth_laboratory
GET {{baseUrl}}/laboratory/findAll?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}


### Criar um Students_subjectives (relacionado ao acadêmico)
# @name create_subjective
POST {{baseUrl}}/students-subjectives/create
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Árvores e Grafos",
  "description": "Árvores e Grafos",
  "season": "2025/2"
}

### Visualização de subjectives
# @name fecth_subjective
GET {{baseUrl}}/students-subjectives/findAll?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}


### Criar um Sub_event (depende do evento e do subjective)
# @name create_sub_event
POST {{baseUrl}}/sub-events/create/{{eventId}}/{{subjectiveId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "teste",
  "description": "Apresentação final dos TCCs",
  "date": "2025-10-01T00:00:00.000Z"
}

### Visualização de sub_events
# @name fecth_sub_event
GET {{baseUrl}}/sub-events/findAll?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}


### Criação de um advice
# @name create_advice
POST {{baseUrl}}/advices/create/{{laboratoryId}}/{{subEventId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "description": "Testes",
  "tier": "low"
}

### Visualização de advices
# @name fecth_advice
GET {{baseUrl}}/advices/findAll?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}