@baseUrl = http://localhost:3000
@authToken = {{authentication.response.body.acess_token}}

# @name create-academic
POST {{baseUrl}}/academics
Content-Type: application/json

{
    "name": "Samuel",
    "email": "samuel11@gmail.com",
    "phone": 412342,
    "RA": 12312412,
    "password": "soft"
}

###

# @name authentication
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "samuel@gmail.com",
    "password": "soft"
}

###

# @name create_event
POST {{baseUrl}}/event
Content-Type: application/json
Authorization: Bearer {{authToken}}