version: '3.8' 

services:
  postgres:
    container_name: verum-clean-pg
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: swordmoon123
      POSTGRES_DB: verum-pg
      PG_DATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres