-- AlterTable
ALTER TABLE "academics" ALTER COLUMN "phone" SET DATA TYPE TEXT,
ALTER COLUMN "RA" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "students" ALTER COLUMN "phone" SET DATA TYPE TEXT,
ALTER COLUMN "RA" SET DATA TYPE TEXT;
